import streamlit as st
st.header("Movies Links")
st.write("I bomma Link - [ibomma](https://men.ibomma.bond/telugu-movies/)")
st.write("Movie  [గుంటూరు కారం] - (https://dev.ibomma.nexus/te-a1cwn/guntur-kaaram-2024-uav2q-telugu-movie-watch-online.html)")
st.write("Movie [Animal](https://men.ibomma.bond/te-a1cwn/animal-2023-u3tch-telugu-movie-watch-online.html)")
st.write("Movie rulz website [movierulz] - (https://ww26.watchmovierulz.to/)")
st.write("Movie [Jailer](https://ww5.ibomma.link/te-a1cwn/jailer-2023-g5dbs-telugu-movie-watch-online.html)")
st.write("Movie [Bro](https://ww5.ibomma.link/te-a1cwn/bro-2023-y6fdv-telugu-movie-watch-online.html)")
st.write("Movie - [Miss shetty Mr polishetty](https://ww26.watchmovierulz.to/miss-shetty-mr-polishetty-2023-telugu/full-movie-watch-online-free-1-6811.html)")
st.write("Movie - [Bhagavath Kesari](https://leo.ibomma.day/d/Bhagavanth-Kesari-2023-sd7S-telugu-movie-watch-online.html)")
st.write("Movie - [Bhola Shankar](https://bet.ibomma.link/te-a1cwn/bholaa-shankar-2023-g6uic-telugu-movie-watch-online.html)")
